<a href="https://colab.research.google.com/github/Maryermarh/click-on-kaduna-dsfp4.0/blob/main/Assignment_compiled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Day 1

#### ONE-DIMENSIONAL ARRAY

In [ ]:
import numpy as np

In [ ]:
#Question 1
patient_age_array = np.array([25, 30, 40, 22, 35, 50, 29, 60, 41, 28])

#Find the average age of the patients
np.mean(patient_age_array)

36.0

In [ ]:
#Question 2
cholestorol_level = np.array([210, 180, 230, 250, 300, 220, 200, 190])

#Identify the highest cholesterol level from the list
np.max(cholestorol_level)

300

In [ ]:
#Question 3
bp_reading = np.array([120, 130, 140, 135, 125, 110, 145, 120, 130, 140, 150, 135])

#Find the standard deviation of blood pressure readings
np.std(bp_reading)

11.055415967851333

In [ ]:
#Question 4
patient_temp = np.array([37.1, 36.5, 37.3, 36.8, 37.0, 38.0, 36.7, 37.2, 36.9, 37.5])

#Calculate the mean temperature for the patient
np.mean(patient_temp)

37.1

In [ ]:
#Question 5
patient_weight = np.array([60, 72, 65, 58, 82, 75, 70, 68, 66, 80])

#Return the reversed order of weights
reverse_weight = patient_weight[::-1]
reverse_weight

array([80, 66, 68, 70, 75, 82, 58, 65, 72, 60])

#### TWO DIMENSIONAL ARRAY

In [ ]:
# Question 6 - 9
patient_data = np.array([[25, 70, 120],
                        [30, 80, 130],
                        [40, 85, 140]])

#Access the blood pressure of the second patient (use index)
patient_data[1,-1]

130

In [ ]:
#Question 10 - 14
blood_tests = np.array([[5.6, 7.1, 6.2, 5.8],
[5.3, 6.9, 7.0, 6.5],
[5.7, 6.5, 6.8, 6.0],
[5.4, 7.0, 6.5, 5.9]])


#The sum of values across each row (representing total test results for each patient)
sum_bloodtests = np.sum(blood_tests, axis = 1)
sum_bloodtests

array([24.7, 25.7, 25. , 24.8])

In [ ]:
#Question 15 - 20
patient_sugar = np.array([[80, 85, 90],
[95, 92, 88],
[85, 83, 82],
[100, 105, 110],
[75, 78, 80]])


#Find the average blood sugar level for the 3rd patient across all visits
average_sugar = np.mean(patient_sugar)
average_sugar

88.53333333333333

In [ ]:
#Question 21 - 24
BMI = np.array([
    [22.1, 23.5],
    [27.8, 28.0],
    [21.2, 20.9]
])
# Perform the element-wise multiplication of BMI and weight (use a weight array: [60, 70, 80])

Weight = np.array([60, 70, 80]).reshape(-1, 1)  # Reshape to column vector

# Element-wise multiplication
result = BMI * Weight
result

array([[1326., 1410.],
       [1946., 1960.],
       [1696., 1672.]])

In [ ]:
#Question 25 - 27
temperature_data = np.array([
    [37.0, 36.5, 37.1, 36.9, 37.0],
    [36.8, 37.3, 37.0, 36.7, 37.2]
])
# Find the maximum temperature for each patient
max_temperature = np.max(temperature_data, axis=1)
print("Maximum temperature for each patient:", max_temperature)

Maximum temperature for each patient: [37.1 37.3]


## Day 2

#### SERIES

In [ ]:
import pandas as pd

In [ ]:
#Question 1
bp_readings = pd.Series([120, 130, 140, 135, 125])

#Find the maximum and minimum blood pressure values
min_bp = bp_readings.min()
max_bp = bp_readings.max()
print(f'maximum BP = {max_bp} \nminimum BP = {min_bp}')

maximum BP = 140 
minimum BP = 120


In [ ]:
#Question 2
cholestorol_level_s= pd.Series([210, 180, 220, 250, 280, 230])

#Filter patients with cholesterol levels above 240
cholestorol_level_s[cholestorol_level_s > 240]

3    250
4    280
dtype: int64

In [ ]:
#Question 3
patient_ages = pd.Series([35, 40, 25, 30, 45, 50, 55, 60, 65, 70])

#Calculate the median age of the patients
patient_ages.median()

47.5

In [ ]:
#Question 4
weight = pd.Series([70, 80, 75, 65, 85])

#Add 5 kg to each patient’s weight
weight += 5
weight

0    75
1    85
2    80
3    70
4    90
dtype: int64

In [ ]:
#Question 5
temp_patient = pd.Series([37.2, 36.8, 37.5, 38.0, 36.6, 37.1, 36.9, 37.3, 37.4, 37.0])

#Calculate the average temperature of all 10 patients
temp_patient.mean()

37.17999999999999

#### DATAFRAME

In [28]:
#Question 6
# Creating the data dictionary
data = {
    'Name': ['John', 'Jane', 'Tom', 'Alice'],
    'Age': [28, 34, 45, 52],
    'Blood Pressure': [120, 130, 140, 150],
    'Cholesterol': [200, 220, 240, 260]}

# Creating the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

    Name  Age  Blood Pressure  Cholesterol
0   John   28             120          200
1   Jane   34             130          220
2    Tom   45             140          240
3  Alice   52             150          260


In [30]:
#cont. of question 6 -10
#filtered_df = df[df['Cholesterol'] > 220]

greather_than_df = df[df['Cholesterol'] > 220]
print (greather_than_df)



    Name  Age  Blood Pressure  Cholesterol
2    Tom   45             140          240
3  Alice   52             150          260


In [31]:
#Question 11
data_patient_info = {
    'Name': ['John', 'Jane', 'Tom', 'Alice'],
    'Age': [28, 34, 45, 52],
    'Height': [1.75, 1.60, 1.80, 1.65],  # Height in meters
    'Weight': [70, 80, 90, 85],  # Weight in kilograms
    'Blood Pressure': [120, 130, 140, 150]
}

# Creating the DataFrame
df = pd.DataFrame(data_patient_info)

# Calculating BMI (BMI = Weight / (Height^2))
df['BMI'] = df['Weight'] / (df['Height'] ** 2)

# Display the updated DataFrame
print(df)

    Name  Age  Height  Weight  Blood Pressure        BMI
0   John   28    1.75      70             120  22.857143
1   Jane   34    1.60      80             130  31.250000
2    Tom   45    1.80      90             140  27.777778
3  Alice   52    1.65      85             150  31.221304


In [32]:
# Question 12 - 15


# Creating the data dictionary with patient blood test results
data_blood_test1 = {
    'Test ID': [1, 2, 3, 4],
    'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
    'Result': [5.6, 6.1, 5.8, 6.3]
}

# Creating the DataFrame
df = pd.DataFrame(data_blood_test1)

# Filtering patients with a test result greater than 6.0
filtered_df = df[df['Result'] > 6.0]

# Display the filtered DataFrame
print(filtered_df)

   Test ID Patient Name  Result
1        2         Jane     6.1
3        4        Alice     6.3


In [33]:
#Question 16
# Creating the data dictionary with patient age, weight, and height
data_patince_BMI = {
    'Age': [28, 34, 45, 52],
    'Weight': [70, 80, 90, 85],
    'Height': [1.75, 1.60, 1.80, 1.65]
}

# Creating the DataFrame
df = pd.DataFrame(data_patince_BMI)

# Calculating the average of each column using df.mean()
average_values = df.mean()

# Display the averages
print(average_values)


Age       39.75
Weight    81.25
Height     1.70
dtype: float64


In [34]:
#Question 17 - 20
 #Creating the data dictionary with treatment details

surgery_treatment = {
    'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
    'Treatment Type': ['Surgery', 'Consultation', 'Surgery', 'Consultation'],
    'Treatment Date': ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01']
}

# Creating the DataFrame
df = pd.DataFrame(surgery_treatment)

# Filtering records where the treatment type is "Surgery"
surgery_records = df[df['Treatment Type'] == 'Surgery']

# Display the filtered records
print(surgery_records)

  Patient Name Treatment Type Treatment Date
0         John        Surgery     2022-01-01
2          Tom        Surgery     2022-03-01
